//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shopthethao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoanAdmin
    {
        public int MaAdmin { get; set; }
        public string TaiKhoan { get; set; }
        public string TenHienThi { get; set; }
        public string Email { get; set; }
        public string MatKhauAdmin { get; set; }
        public Nullable<int> MaLoaiAdmin { get; set; }
    
        public virtual LoaiAdmin LoaiAdmin { get; set; }
    }
}
